# Generated by Django 3.0.3 on 2020-12-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetTable',
            fields=[
                ('tweet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('timeline_screen_name', models.CharField(max_length=100)),
                ('tweet_text', models.CharField(max_length=1000)),
                ('tweet_entities', models.CharField(max_length=10000)),
                ('tweet_screen_name', models.CharField(max_length=100)),
                ('tweet_user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=200)),
                ('session_secret', models.CharField(max_length=200)),
                ('screen_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('session_key', 'session_secret', 'screen_name')},
            },
        ),
    ]
