# Generated by Django 2.2.17 on 2020-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettable',
            name='tweet_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
